using Test

include("test_norm_perception.jl")
include("test_utility_solver.jl")
include("test_household_bargaining.jl")
include("test_decision_invariants.jl")
include("test_statistics.jl")
include("test_shocks.jl")
include("test_run_support.jl")
include("test_run_spec.jl")
include("test_run_pipeline.jl")
include("test_run_logging.jl")
include("test_run_model.jl")
include("test_run_example.jl")
include("test_threading.jl")
include("test_bargaining_equivalence.jl")
include("test_bargain_certificate.jl")
include("test_interval_certificate.jl")
include("test_transfer_search.jl")
include("test_transfer_search_reduction.jl")
include("test_transfer_local_search.jl")
